server:
  port: 8099

spring:
  main:
    allow-circular-references: true
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dbuser
    username: postgres
    password: arief6696
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true